### Get All Data
POST http://localhost:4000/graphql HTTP/1.1
Content-Type: application/json
X-Request-Type: GraphQL

query Query {
  getAllBooks {
    _id
    title
    author
    description
    release_year
    genre
  }
}

### Get One Data
POST http://localhost:4000/graphql HTTP/1.1
Content-Type: application/json
X-Request-Type: GraphQL

query {
  getBook(_id: "612f897e207b3244cd80a21b") {
    _id,
    title,
    description,
    release_year
  }
}

### Update Data
POST http://localhost:4000/graphql HTTP/1.1
Content-Type: application/json
X-Request-Type: GraphQL

mutation {
  updateBook(
    _id: "612f897e207b3244cd80a21b",
    title: "ini update title loh",
    author: "yeppi"
    ) {
      _id,
      title
    }
}

### Delete Data
POST http://localhost:4000/graphql HTTP/1.1
Content-Type: application/json
X-Request-Type: GraphQL

mutation {
  deleteBook(_id: "612f897b207b3244cd80a219")
}